### PR TITLE
Cameraboard v02 Stack Updates

### PR DESCRIPTION
**Pull request by NeilKhera**

### CODE REVIEW

**Comment by NeilKhera** [comment]
@g-savant It'd be great if you could document all the changes you made in a reply here. I can also make a post after to explain my edits. See this post for an idea:
https://github.com/PyCubed-Mini/avionics-motherboard/pull/6

**Comment by g-savant** [comment]
Edits made: Changed board outline to match the Stack Assembly model in Fusion. Repositioned and rerouted components on board. Added microSD card reader and associated circuitry.

**Comment by jbwillis** [comment]
- [ ]  space out nicla power switch circuit
- [x] update mainboard connector
- [x] add -Y connector

**Comment by jbwillis** [comment]
We need to change the positions of the connectors on this board. 

- [ ] The centerline of the mainboard-cameraboard (20 pin) connector doesn't align between the two boards.
- [ ] The solar -Y connector will interfere with the bottom rails - it needs to be shifted towards the center of the board.

image

image

image

**Pull request closed without merging**
